[package]
name = "craftsql-store-cached"
version.workspace = true
edition.workspace = true

[dependencies]
craftsql-core = { path = "../core" }
craftsql-store-local = { path = "../store-local" }
thiserror = "2"
hex = "0.4"
bincode = "1.3"

[dev-dependencies]
tempfile = "3"