[package]
name = "craftsql-objstore"
version.workspace = true
edition.workspace = true

[dependencies]
craftsql-core = { path = "../core" }
hex = "0.4"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
